apiVersion: apps/v1
kind: Deployment
metadata:
  name: crimemap
  namespace: rbda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crimemap
  template:
    metadata:
      labels:
        app: crimemap
    spec:
      containers:
      - args:
        - analytics/online/config/crimemap.release.yaml
        image: IMAGE_NAME
        name: crimemap
        ports:
        - containerPort: 8079
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8090"
    prometheus.io/scrape: "true"
  name: crimemap
  namespace: rbda
spec:
  ports:
  - port: 8079
    protocol: TCP
    name: grpc
  - port: 8080
    protocol: TCP
    name: grpcweb
  - http: 8081
    protocol: TCP
    name: grpc
  selector:
    app: crimemap
  type: LoadBalancer