// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analytics/online/proto/crimemap_service/crimemap_service.proto

package crimemap_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCrimesRequest struct {
	TimeMin              int64    `protobuf:"varint,1,opt,name=time_min,json=timeMin,proto3" json:"time_min,omitempty"`
	TimeMax              int64    `protobuf:"varint,2,opt,name=time_max,json=timeMax,proto3" json:"time_max,omitempty"`
	LongitudeMin         float64  `protobuf:"fixed64,3,opt,name=longitude_min,json=longitudeMin,proto3" json:"longitude_min,omitempty"`
	LongitudeMax         float64  `protobuf:"fixed64,4,opt,name=longitude_max,json=longitudeMax,proto3" json:"longitude_max,omitempty"`
	LatitudeMin          float64  `protobuf:"fixed64,5,opt,name=latitude_min,json=latitudeMin,proto3" json:"latitude_min,omitempty"`
	LatitudeMax          float64  `protobuf:"fixed64,6,opt,name=latitude_max,json=latitudeMax,proto3" json:"latitude_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCrimesRequest) Reset()         { *m = GetCrimesRequest{} }
func (m *GetCrimesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCrimesRequest) ProtoMessage()    {}
func (*GetCrimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05817e490cd8, []int{0}
}

func (m *GetCrimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCrimesRequest.Unmarshal(m, b)
}
func (m *GetCrimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCrimesRequest.Marshal(b, m, deterministic)
}
func (m *GetCrimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCrimesRequest.Merge(m, src)
}
func (m *GetCrimesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCrimesRequest.Size(m)
}
func (m *GetCrimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCrimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCrimesRequest proto.InternalMessageInfo

func (m *GetCrimesRequest) GetTimeMin() int64 {
	if m != nil {
		return m.TimeMin
	}
	return 0
}

func (m *GetCrimesRequest) GetTimeMax() int64 {
	if m != nil {
		return m.TimeMax
	}
	return 0
}

func (m *GetCrimesRequest) GetLongitudeMin() float64 {
	if m != nil {
		return m.LongitudeMin
	}
	return 0
}

func (m *GetCrimesRequest) GetLongitudeMax() float64 {
	if m != nil {
		return m.LongitudeMax
	}
	return 0
}

func (m *GetCrimesRequest) GetLatitudeMin() float64 {
	if m != nil {
		return m.LatitudeMin
	}
	return 0
}

func (m *GetCrimesRequest) GetLatitudeMax() float64 {
	if m != nil {
		return m.LatitudeMax
	}
	return 0
}

type Crime struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crime) Reset()         { *m = Crime{} }
func (m *Crime) String() string { return proto.CompactTextString(m) }
func (*Crime) ProtoMessage()    {}
func (*Crime) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05817e490cd8, []int{1}
}

func (m *Crime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crime.Unmarshal(m, b)
}
func (m *Crime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crime.Marshal(b, m, deterministic)
}
func (m *Crime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crime.Merge(m, src)
}
func (m *Crime) XXX_Size() int {
	return xxx_messageInfo_Crime.Size(m)
}
func (m *Crime) XXX_DiscardUnknown() {
	xxx_messageInfo_Crime.DiscardUnknown(m)
}

var xxx_messageInfo_Crime proto.InternalMessageInfo

func (m *Crime) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Crime) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Crime) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Crime) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetCrimesResponse struct {
	Crimes               []*Crime `protobuf:"bytes,1,rep,name=crimes,proto3" json:"crimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCrimesResponse) Reset()         { *m = GetCrimesResponse{} }
func (m *GetCrimesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCrimesResponse) ProtoMessage()    {}
func (*GetCrimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5eda05817e490cd8, []int{2}
}

func (m *GetCrimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCrimesResponse.Unmarshal(m, b)
}
func (m *GetCrimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCrimesResponse.Marshal(b, m, deterministic)
}
func (m *GetCrimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCrimesResponse.Merge(m, src)
}
func (m *GetCrimesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCrimesResponse.Size(m)
}
func (m *GetCrimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCrimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCrimesResponse proto.InternalMessageInfo

func (m *GetCrimesResponse) GetCrimes() []*Crime {
	if m != nil {
		return m.Crimes
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCrimesRequest)(nil), "crimemap.service.GetCrimesRequest")
	proto.RegisterType((*Crime)(nil), "crimemap.service.Crime")
	proto.RegisterType((*GetCrimesResponse)(nil), "crimemap.service.GetCrimesResponse")
}

func init() {
	proto.RegisterFile("analytics/online/proto/crimemap_service/crimemap_service.proto", fileDescriptor_5eda05817e490cd8)
}

var fileDescriptor_5eda05817e490cd8 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xea, 0x40,
	0x10, 0xc0, 0xdf, 0x3e, 0xfe, 0x3c, 0x18, 0x78, 0x09, 0xee, 0xc5, 0x4a, 0x3c, 0xd4, 0x72, 0xe1,
	0xd4, 0x26, 0x78, 0x37, 0x06, 0x4d, 0x3c, 0x71, 0xe9, 0xc1, 0x83, 0x17, 0x32, 0x94, 0x0d, 0x8c,
	0x69, 0x77, 0x6b, 0x77, 0xab, 0xd5, 0x4f, 0xea, 0xc7, 0x31, 0x5d, 0x4a, 0x81, 0x92, 0x78, 0xeb,
	0xfe, 0xf6, 0x37, 0xd3, 0x99, 0x9d, 0x81, 0x3b, 0x94, 0x18, 0x7f, 0x1a, 0x8a, 0x74, 0xa0, 0x64,
	0x4c, 0x52, 0x04, 0x69, 0xa6, 0x8c, 0x0a, 0xa2, 0x8c, 0x12, 0x91, 0x60, 0xba, 0xd4, 0x22, 0x7b,
	0xa7, 0x48, 0x9c, 0x01, 0xdf, 0x7a, 0x7c, 0xb4, 0xe7, 0x7e, 0xc5, 0xbd, 0x6f, 0x06, 0xa3, 0x27,
	0x61, 0x1e, 0x4a, 0xae, 0x43, 0xf1, 0x96, 0x0b, 0x6d, 0xf8, 0x15, 0xf4, 0x0c, 0x25, 0x62, 0x99,
	0x90, 0x74, 0x98, 0xcb, 0xa6, 0xad, 0xf0, 0x5f, 0x79, 0x5e, 0x90, 0x3c, 0x5c, 0x61, 0xe1, 0xfc,
	0x3d, 0xba, 0xc2, 0x82, 0x4f, 0xe0, 0x7f, 0xac, 0xe4, 0x86, 0x4c, 0xbe, 0xde, 0x85, 0xb6, 0x5c,
	0x36, 0x65, 0xe1, 0xb0, 0x86, 0x65, 0xfc, 0xa9, 0x84, 0x85, 0xd3, 0x6e, 0x4a, 0x58, 0xf0, 0x1b,
	0x18, 0xc6, 0x68, 0x0e, 0x89, 0x3a, 0xd6, 0x19, 0xec, 0x59, 0x99, 0xe7, 0x44, 0xc1, 0xc2, 0xe9,
	0x36, 0x14, 0x2c, 0xbc, 0x0f, 0xe8, 0xd8, 0xb6, 0x38, 0x87, 0x76, 0x59, 0x63, 0xd5, 0x8a, 0xfd,
	0xe6, 0xd7, 0xd0, 0xaf, 0x7f, 0x69, 0x1b, 0x61, 0xe1, 0x01, 0xf0, 0x31, 0xf4, 0xf6, 0x99, 0xaa,
	0x2e, 0xea, 0x33, 0x77, 0x61, 0xb0, 0x16, 0x3a, 0xca, 0x28, 0x35, 0xa4, 0xa4, 0xad, 0xbf, 0x1f,
	0x1e, 0x23, 0xef, 0x11, 0x2e, 0x8e, 0x9e, 0x54, 0xa7, 0x4a, 0x6a, 0xc1, 0x03, 0xe8, 0xda, 0xc7,
	0xd7, 0x0e, 0x73, 0x5b, 0xd3, 0xc1, 0xec, 0xd2, 0x6f, 0xce, 0xc2, 0xb7, 0x11, 0x61, 0xa5, 0xcd,
	0x56, 0xd0, 0xb3, 0x60, 0x81, 0x29, 0x7f, 0x86, 0x7e, 0x9d, 0x91, 0x7b, 0xe7, 0x91, 0xcd, 0x09,
	0x8e, 0x27, 0xbf, 0x3a, 0xbb, 0x92, 0xbc, 0x3f, 0xf3, 0xf9, 0xcb, 0xfd, 0x86, 0xcc, 0x36, 0x5f,
	0xf9, 0x91, 0x4a, 0x82, 0x57, 0xc2, 0x38, 0x97, 0x5f, 0x5b, 0xa4, 0x7a, 0x7f, 0x82, 0xb3, 0x85,
	0x6b, 0x6e, 0xd6, 0xaa, 0x6b, 0x57, 0xeb, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x26, 0xcc,
	0xc1, 0x9c, 0x02, 0x00, 0x00,
}
